"""refactor order and customer models

Revision ID: 37316d9ce11f
Revises: 055731624f6a
Create Date: 2025-08-08 23:42:43.555998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37316d9ce11f'
down_revision: Union[str, Sequence[str], None] = '055731624f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uniqueIdentifier', sa.String(length=100), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_info_uniqueIdentifier'), 'customer_info', ['uniqueIdentifier'], unique=True)
    op.add_column('carts', sa.Column('uniqueIdentifier', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('carts_cart_token_key'), 'carts', type_='unique')
    op.drop_constraint(op.f('carts_email_key'), 'carts', type_='unique')
    op.create_unique_constraint("uq_carts_unique_identifier", 'carts', ['uniqueIdentifier'])
    op.drop_column('carts', 'email')
    op.drop_column('carts', 'cart_token')
    op.add_column('orders', sa.Column('uniqueIdentifier', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.create_foreign_key("fk_orders_customer_id", 'orders', 'customer_info', ['customer_id'], ['id'])
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'customer_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint("fk_orders_customer_id", 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_column('orders', 'uniqueIdentifier')
    op.add_column('carts', sa.Column('cart_token', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint("uq_carts_unique_identifier", 'carts', type_='unique')
    op.create_unique_constraint(op.f('carts_email_key'), 'carts', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('carts_cart_token_key'), 'carts', ['cart_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('carts', 'uniqueIdentifier')
    op.drop_index(op.f('ix_customer_info_uniqueIdentifier'), table_name='customer_info')
    op.drop_table('customer_info')
    # ### end Alembic commands ###
