"""add relationship between order and order item

Revision ID: 055731624f6a
Revises: 4118e8ef4658
Create Date: 2025-08-08 23:16:40.266937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055731624f6a'
down_revision: Union[str, Sequence[str], None] = '4118e8ef4658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_order_items_order_id', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_items_order_id', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
