"""Add ingredients to pizza

Revision ID: a71461fd0283
Revises: 424803f46c8e
Create Date: 2025-08-08 17:07:35.189336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71461fd0283'
down_revision: Union[str, Sequence[str], None] = '424803f46c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizzas', sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizzas', 'ingredients')
    # ### end Alembic commands ###
