name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint with ruff
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Type check with mypy
        run: |
          poetry run mypy .

      - name: Test with pytest
        run: |
          poetry run pytest